"""add question_pdf_url

Revision ID: 3abe6209cf75
Revises: 14a512366c74
Create Date: 2026-04-19 20:24:23.856760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abe6209cf75'
down_revision = '14a512366c74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aptitude_questions', sa.Column('question_pdf_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aptitude_questions', 'question_pdf_url')
    # ### end Alembic commands ###
